.nh
.TH "mailcat" "1" "Nov 2021" "" ""

.SH NAME
.PP
mailcat \- A mail and smtp test tool


.SH SYNOPSIS
.PP
\fBmailcat [flags]\fP


.SH DESCRIPTION
.PP
A mail and smtp test tool


.SH OPTIONS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.mailcat.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for mailcat


.SH SEE ALSO
.PP
\fBmailcat\-completion(1)\fP, \fBmailcat\-doc(1)\fP, \fBmailcat\-fmt(1)\fP, \fBmailcat\-send(1)\fP
