.nh
.TH "mailcat" "1" "Apr 2023" "" ""

.SH NAME
.PP
mailcat-doc - generate documentation for mailcat


.SH SYNOPSIS
.PP
\fBmailcat doc [flags]\fP


.SH DESCRIPTION
.PP
generate documentation for mailcat in several formats


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBmailcat(1)\fP, \fBmailcat-doc-man(1)\fP, \fBmailcat-doc-md(1)\fP
