.nh
.TH "mailcat" "1" "Apr 2023" "" ""

.SH NAME
.PP
mailcat - A mail and smtp test tool


.SH SYNOPSIS
.PP
\fBmailcat [flags]\fP


.SH DESCRIPTION
.PP
A mail and smtp test tool


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for mailcat


.SH SEE ALSO
.PP
\fBmailcat-completion(1)\fP, \fBmailcat-doc(1)\fP, \fBmailcat-fmt(1)\fP, \fBmailcat-send(1)\fP
