.nh
.TH "mailcat" "1" "Nov 2021" "" ""

.SH NAME
.PP
mailcat\-doc \- generate documentation for mailcat


.SH SYNOPSIS
.PP
\fBmailcat doc [flags]\fP


.SH DESCRIPTION
.PP
generate documentation for mailcat in several formats


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for doc

.PP
\fB\-o\fP, \fB\-\-output\fP="."
	documentation output path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.mailcat.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output


.SH SEE ALSO
.PP
\fBmailcat(1)\fP, \fBmailcat\-doc\-man(1)\fP, \fBmailcat\-doc\-md(1)\fP
